// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import PieChartOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/PieChartOutlined';
import RadarChartOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
import LineChartOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/LineChartOutlined';
import HomeOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import DashboardOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ApartmentOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ApartmentOutlined';
import FileTextOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import ProfileOutlined from '/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
export default { CrownOutlined, PieChartOutlined, RadarChartOutlined, LineChartOutlined, HomeOutlined, DashboardOutlined, ApartmentOutlined, FileTextOutlined, ProfileOutlined };
