// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import HomeOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import DashboardOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ApartmentOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ApartmentOutlined';
import ProfileOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import FileTextOutlined from 'C:/Users/yzh/Desktop/feature_map_text/myapp/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
export default { CrownOutlined, HomeOutlined, DashboardOutlined, ApartmentOutlined, ProfileOutlined, FileTextOutlined };
