// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
/// <reference types="/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@ant-design/pro-components" />


import {
  Link, useLocation, useNavigate, Outlet, useAppData, matchRoutes,
  type IRoute
} from '@umijs/max';
import React, { useMemo } from 'react';
import {
  ProLayout,
} from "/Users/torch/torch/opt/career-planning-agent/myapp/node_modules/@ant-design/pro-components";
import './Layout.css';
import Logo from './Logo';
import Exception from './Exception';
import { getRightRenderContent } from './rightRender';
import { useModel } from '@@/plugin-model';
import { useAccessMarkedRoutes } from '@@/plugin-access';
import { useIntl } from '@@/plugin-locale';

// 过滤出需要显示的路由, 这里的filterFn 指 不希望显示的层级
const filterRoutes = (routes: IRoute[], filterFn: (route: IRoute) => boolean) => {
  if (routes.length === 0) {
    return []
  }

  let newRoutes = []
  for (const route of routes) {
    const newRoute = {...route };
    if (filterFn(route)) {
      if (Array.isArray(newRoute.routes)) {
        newRoutes.push(...filterRoutes(newRoute.routes, filterFn))
      }
    } else {
      if (Array.isArray(newRoute.children)) {
        newRoute.children = filterRoutes(newRoute.children, filterFn);
        newRoute.routes = newRoute.children;
      }
      newRoutes.push(newRoute);
    }
  }

  return newRoutes;
}

// 格式化路由 处理因 wrapper 导致的 菜单 path 不一致
const mapRoutes = (routes: IRoute[]) => {
  if (routes.length === 0) {
    return []
  }
  return routes.map(route => {
    // 需要 copy 一份, 否则会污染原始数据
    const newRoute = {...route}
    if (route.originPath) {
      newRoute.path = route.originPath
    }

    if (Array.isArray(route.routes)) {
      newRoute.routes = mapRoutes(route.routes);
    }

    if (Array.isArray(route.children)) {
      newRoute.children = mapRoutes(route.children);
    }

    return newRoute
  })
}

export default (props: any) => {
  const location = useLocation();
  const navigate = useNavigate();
  const { clientRoutes, pluginManager } = useAppData();
  const initialInfo = (useModel && useModel('@@initialState')) || {
    initialState: undefined,
    loading: false,
    setInitialState: null,
  };
  const { initialState, loading, setInitialState } = initialInfo;
  const userConfig = {
  "locale": true,
  "navTheme": "light",
  "colorPrimary": "#c96442",
  "layout": "top",
  "contentWidth": "Fixed",
  "fixedHeader": true,
  "fixSiderbar": true,
  "splitMenus": false,
  "colorWeak": false,
  "title": "大学生职业规划智能体",
  "pwa": true,
  "logo": "/images/logo/brand-logo.png",
  "iconfontUrl": "",
  "token": {
    "colorPrimary": "#c96442",
    "colorPrimaryHover": "#d97757",
    "colorPrimaryActive": "#b05535",
    "colorPrimaryBg": "#faf0eb",
    "colorPrimaryBgHover": "#f3e5db",
    "colorSuccess": "#4a7c3f",
    "colorSuccessBg": "#eef5ec",
    "colorSuccessBorder": "#b8d4b0",
    "colorWarning": "#B07800",
    "colorWarningBg": "#FDF6E3",
    "colorWarningBorder": "#F0C850",
    "colorError": "#b53333",
    "colorErrorBg": "#faeaea",
    "colorErrorBorder": "#d9a0a0",
    "colorInfo": "#c96442",
    "colorInfoBg": "#faf0eb",
    "colorInfoBorder": "#e8c8b8",
    "colorText": "#141413",
    "colorTextSecondary": "#5e5d59",
    "colorTextTertiary": "#87867f",
    "colorTextQuaternary": "#b0aea5",
    "colorBorder": "#f0eee6",
    "colorBorderSecondary": "#f5f4ed",
    "colorBgBase": "#FFFFFF",
    "colorBgContainer": "#faf9f5",
    "colorBgElevated": "#faf9f5",
    "colorBgLayout": "#f5f4ed",
    "colorBgSpotlight": "#f5f4ed",
    "fontSize": 14,
    "fontSizeSM": 12,
    "fontSizeLG": 16,
    "fontSizeXL": 20,
    "fontSizeHeading1": 24,
    "fontSizeHeading2": 20,
    "fontSizeHeading3": 16,
    "fontSizeHeading4": 14,
    "fontSizeHeading5": 12,
    "fontWeightRegular": 400,
    "fontWeightMedium": 500,
    "fontWeightSemibold": 600,
    "fontWeightBold": 700,
    "fontWeightDisplay": 900,
    "fontFamily": "-apple-system, BlinkMacSystemFont, \"PingFang SC\", \"Segoe UI\", Roboto, sans-serif",
    "fontFamilyCode": "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
    "fontFamilyHeading": "\"STSongti SC\", \"SimSun\", \"Songti SC\", \"Noto Serif SC\", Georgia, serif",
    "lineHeight": 1.6,
    "lineHeightSM": 1.5,
    "lineHeightLG": 1.8,
    "padding": 16,
    "paddingSM": 12,
    "paddingLG": 24,
    "paddingXS": 8,
    "paddingXXS": 4,
    "margin": 16,
    "marginSM": 12,
    "marginLG": 24,
    "marginXS": 8,
    "marginXXS": 4,
    "borderRadius": 8,
    "borderRadiusSM": 4,
    "borderRadiusLG": 12,
    "borderRadiusXS": 2,
    "borderRadiusOuter": 4,
    "boxShadow": "rgba(0, 0, 0, 0.05) 0px 4px 24px",
    "boxShadowSecondary": "0 1px 2px rgba(0, 0, 0, 0.06)",
    "authLeftGradient": "linear-gradient(160deg, #f5f4ed 0%, #ece9df 50%, #e8e6dc 100%)",
    "controlHeight": 36,
    "controlHeightSM": 28,
    "controlHeightLG": 44,
    "menuHorizontalPadding": 16,
    "menuItemPaddingInline": 16,
    "menuItemBorderRadius": 0,
    "menuIconMarginInline": 8,
    "menuIconSize": 14,
    "menuItemSelectedColor": "#c96442",
    "menuItemSelectedBg": "#faf0eb",
    "menuItemHoverColor": "#141413",
    "menuItemHoverBg": "#f5f4ed",
    "menuItemColor": "#5e5d59",
    "menuBg": "#faf9f5",
    "menuSubMenuItemBg": "#faf9f5",
    "menuDarkItemSelectedColor": "#FFFFFF",
    "menuDarkItemSelectedBg": "#c96442",
    "menuDarkItemHoverBg": "rgba(255,255,255,0.1)",
    "menuCollapsedWidth": 80,
    "menuCollapsedIconSize": 16
  }
};
const { formatMessage } = useIntl();
  const runtimeConfig = pluginManager.applyPlugins({
    key: 'layout',
    type: 'modify',
    initialValue: {
      ...initialInfo
    },
  });


  // 现在的 layout 及 wrapper 实现是通过父路由的形式实现的, 会导致路由数据多了冗余层级, proLayout 消费时, 无法正确展示菜单, 这里对冗余数据进行过滤操作
  const newRoutes = filterRoutes(clientRoutes.filter(route => route.id === 'ant-design-pro-layout'), (route) => {
    return (!!route.isLayout && route.id !== 'ant-design-pro-layout') || !!route.isWrapper;
  })
  const [route] = useAccessMarkedRoutes(mapRoutes(newRoutes));

  const matchedRoute = useMemo(() => matchRoutes(route.children, location.pathname)?.pop?.()?.route, [location.pathname]);

  return (
    <ProLayout
      route={route}
      location={location}
      title={userConfig.title || 'ant-design-pro'}
      navTheme="dark"
      siderWidth={256}
      onMenuHeaderClick={(e) => {
        e.stopPropagation();
        e.preventDefault();
        navigate('/');
      }}
      formatMessage={userConfig.formatMessage || formatMessage}
      menu={{ locale: userConfig.locale }}
      logo={Logo}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl || menuItemProps.children) {
          return defaultDom;
        }
        if (menuItemProps.path && location.pathname !== menuItemProps.path) {
          return (
            // handle wildcard route path, for example /slave/* from qiankun
            <Link to={menuItemProps.path.replace('/*', '')} target={menuItemProps.target}>
              {defaultDom}
            </Link>
          );
        }
        return defaultDom;
      }}
      itemRender={(route, _, routes) => {
        const { breadcrumbName, title, path } = route;
        const label = title || breadcrumbName
        const last = routes[routes.length - 1]
        if (last) {
          if (last.path === path || last.linkPath === path) {
            return <span>{label}</span>;
          }
        }
        return <Link to={path}>{label}</Link>;
      }}
      disableContentMargin
      fixSiderbar
      fixedHeader
      {...runtimeConfig}
      rightContentRender={
        runtimeConfig.rightContentRender !== false &&
        ((layoutProps) => {
          const dom = getRightRenderContent({
            runtimeConfig,
            loading,
            initialState,
            setInitialState,
          });
          if (runtimeConfig.rightContentRender) {
            return runtimeConfig.rightContentRender(layoutProps, dom, {
              // BREAK CHANGE userConfig > runtimeConfig
              userConfig,
              runtimeConfig,
              loading,
              initialState,
              setInitialState,
            });
          }
          return dom;
        })
      }
    >
      <Exception
        route={matchedRoute}
        noFound={runtimeConfig?.noFound}
        notFound={runtimeConfig?.notFound}
        unAccessible={runtimeConfig?.unAccessible}
        noAccessible={runtimeConfig?.noAccessible}
      >
        {runtimeConfig.childrenRender
          ? runtimeConfig.childrenRender(<Outlet />, props)
          : <Outlet />
        }
      </Exception>
    </ProLayout>
  );
}
