-- P5 CollectiveWisdom seed data
-- Idempotent: uses INSERT OR IGNORE, safe to run multiple times

-- ── Entities (~50) ──────────────────────────────────────────────

INSERT OR IGNORE INTO cw_entities (id, entity_type, entity_name, properties_json) VALUES
-- Skills
('cw_skill_python', 'skill', 'Python', '{"category":"programming_language","difficulty":"beginner"}'),
('cw_skill_sql', 'skill', 'SQL', '{"category":"database","difficulty":"beginner"}'),
('cw_skill_java', 'skill', 'Java', '{"category":"programming_language","difficulty":"intermediate"}'),
('cw_skill_javascript', 'skill', 'JavaScript', '{"category":"programming_language","difficulty":"beginner"}'),
('cw_skill_machine_learning', 'skill', '机器学习', '{"category":"ai","difficulty":"advanced"}'),
('cw_skill_deep_learning', 'skill', '深度学习', '{"category":"ai","difficulty":"advanced"}'),
('cw_skill_data_analysis', 'skill', '数据分析', '{"category":"analytics","difficulty":"intermediate"}'),
('cw_skill_excel', 'skill', 'Excel', '{"category":"office","difficulty":"beginner"}'),
('cw_skill_linux', 'skill', 'Linux', '{"category":"system","difficulty":"intermediate"}'),
('cw_skill_git', 'skill', 'Git', '{"category":"devops","difficulty":"beginner"}'),
('cw_skill_docker', 'skill', 'Docker', '{"category":"devops","difficulty":"intermediate"}'),
('cw_skill_go', 'skill', 'Go', '{"category":"programming_language","difficulty":"intermediate"}'),
('cw_skill_cpp', 'skill', 'C++', '{"category":"programming_language","difficulty":"intermediate"}'),
('cw_skill_react', 'skill', 'React', '{"category":"frontend","difficulty":"intermediate"}'),
('cw_skill_vue', 'skill', 'Vue', '{"category":"frontend","difficulty":"beginner"}'),
('cw_skill_spring', 'skill', 'Spring Boot', '{"category":"backend","difficulty":"intermediate"}'),
('cw_skill_django', 'skill', 'Django', '{"category":"backend","difficulty":"intermediate"}'),
('cw_skill_communication', 'skill', '沟通表达', '{"category":"soft_skill","difficulty":"intermediate"}'),
('cw_skill_teamwork', 'skill', '团队协作', '{"category":"soft_skill","difficulty":"intermediate"}'),
('cw_skill_project_management', 'skill', '项目管理', '{"category":"soft_skill","difficulty":"intermediate"}'),
-- Roles
('cw_role_data_analyst', 'role', '数据分析师', '{"industry":"互联网","avg_salary":"15-25K"}'),
('cw_role_backend_engineer', 'role', '后端开发工程师', '{"industry":"互联网","avg_salary":"20-35K"}'),
('cw_role_frontend_engineer', 'role', '前端开发工程师', '{"industry":"互联网","avg_salary":"18-30K"}'),
('cw_role_algorithm_engineer', 'role', '算法工程师', '{"industry":"互联网","avg_salary":"25-50K"}'),
('cw_role_product_manager', 'role', '产品经理', '{"industry":"互联网","avg_salary":"18-35K"}'),
('cw_role_test_engineer', 'role', '测试工程师', '{"industry":"互联网","avg_salary":"15-25K"}'),
('cw_role_devops_engineer', 'role', '运维开发工程师', '{"industry":"互联网","avg_salary":"20-35K"}'),
('cw_role_data_scientist', 'role', '数据科学家', '{"industry":"互联网","avg_salary":"25-45K"}'),
('cw_role_fullstack_engineer', 'role', '全栈开发工程师', '{"industry":"互联网","avg_salary":"20-38K"}'),
('cw_role_ux_designer', 'role', 'UX设计师', '{"industry":"互联网","avg_salary":"15-28K"}'),
-- Industries
('cw_industry_internet', 'industry', '互联网/IT', '{"growth_rate":"high"}'),
('cw_industry_finance', 'industry', '金融', '{"growth_rate":"stable"}'),
('cw_industry_education', 'industry', '教育', '{"growth_rate":"stable"}'),
('cw_industry_healthcare', 'industry', '医疗健康', '{"growth_rate":"high"}'),
('cw_industry_ecommerce', 'industry', '电子商务', '{"growth_rate":"high"}'),
('cw_industry_manufacturing', 'industry', '制造业', '{"growth_rate":"stable"}'),
-- Majors
('cw_major_cs', 'major', '计算机科学与技术', '{"degree":"bachelor"}'),
('cw_major_se', 'major', '软件工程', '{"degree":"bachelor"}'),
('cw_major_ds', 'major', '数据科学', '{"degree":"bachelor"}'),
('cw_major_ee', 'major', '电子信息工程', '{"degree":"bachelor"}'),
('cw_major_math', 'major', '数学与应用数学', '{"degree":"bachelor"}'),
('cw_major_stat', 'major', '统计学', '{"degree":"bachelor"}'),
('cw_major_ai', 'major', '人工智能', '{"degree":"bachelor"}'),
('cw_major_is', 'major', '信息管理与信息系统', '{"degree":"bachelor"}'),
('cw_major_auto', 'major', '自动化', '{"degree":"bachelor"}'),
('cw_major_comm', 'major', '通信工程', '{"degree":"bachelor"}'),
('cw_major_finance', 'major', '金融学', '{"degree":"bachelor"}'),
('cw_major_ecom', 'major', '电子商务', '{"degree":"bachelor"}'),
('cw_major_design', 'major', '数字媒体技术', '{"degree":"bachelor"}'),
('cw_major_physics', 'major', '应用物理学', '{"degree":"bachelor"}');

-- ── Relations (~120) ─────────────────────────────────────────────

INSERT OR IGNORE INTO cw_relations (id, from_entity_id, to_entity_id, relation_type) VALUES
-- CS major → skills
('cw_rel_cs_python', 'cw_major_cs', 'cw_skill_python', 'required_by'),
('cw_rel_cs_sql', 'cw_major_cs', 'cw_skill_sql', 'required_by'),
('cw_rel_cs_java', 'cw_major_cs', 'cw_skill_java', 'required_by'),
('cw_rel_cs_linux', 'cw_major_cs', 'cw_skill_linux', 'required_by'),
('cw_rel_cs_git', 'cw_major_cs', 'cw_skill_git', 'required_by'),
('cw_rel_cs_cpp', 'cw_major_cs', 'cw_skill_cpp', 'required_by'),
('cw_rel_cs_js', 'cw_major_cs', 'cw_skill_javascript', 'related_to'),
('cw_rel_cs_ml', 'cw_major_cs', 'cw_skill_machine_learning', 'related_to'),
-- SE major → skills
('cw_rel_se_java', 'cw_major_se', 'cw_skill_java', 'required_by'),
('cw_rel_se_python', 'cw_major_se', 'cw_skill_python', 'required_by'),
('cw_rel_se_sql', 'cw_major_se', 'cw_skill_sql', 'required_by'),
('cw_rel_se_git', 'cw_major_se', 'cw_skill_git', 'required_by'),
('cw_rel_se_js', 'cw_major_se', 'cw_skill_javascript', 'required_by'),
('cw_rel_se_linux', 'cw_major_se', 'cw_skill_linux', 'required_by'),
('cw_rel_se_docker', 'cw_major_se', 'cw_skill_docker', 'related_to'),
('cw_rel_se_spring', 'cw_major_se', 'cw_skill_spring', 'related_to'),
-- DS major → skills
('cw_rel_ds_python', 'cw_major_ds', 'cw_skill_python', 'required_by'),
('cw_rel_ds_sql', 'cw_major_ds', 'cw_skill_sql', 'required_by'),
('cw_rel_ds_da', 'cw_major_ds', 'cw_skill_data_analysis', 'required_by'),
('cw_rel_ds_ml', 'cw_major_ds', 'cw_skill_machine_learning', 'required_by'),
('cw_rel_ds_excel', 'cw_major_ds', 'cw_skill_excel', 'required_by'),
('cw_rel_ds_dl', 'cw_major_ds', 'cw_skill_deep_learning', 'related_to'),
-- AI major → skills
('cw_rel_ai_python', 'cw_major_ai', 'cw_skill_python', 'required_by'),
('cw_rel_ai_ml', 'cw_major_ai', 'cw_skill_machine_learning', 'required_by'),
('cw_rel_ai_dl', 'cw_major_ai', 'cw_skill_deep_learning', 'required_by'),
('cw_rel_ai_sql', 'cw_major_ai', 'cw_skill_sql', 'required_by'),
('cw_rel_ai_git', 'cw_major_ai', 'cw_skill_git', 'required_by'),
('cw_rel_ai_linux', 'cw_major_ai', 'cw_skill_linux', 'related_to'),
-- EE major → skills
('cw_rel_ee_cpp', 'cw_major_ee', 'cw_skill_cpp', 'required_by'),
('cw_rel_ee_python', 'cw_major_ee', 'cw_skill_python', 'required_by'),
('cw_rel_ee_linux', 'cw_major_ee', 'cw_skill_linux', 'required_by'),
('cw_rel_ee_git', 'cw_major_ee', 'cw_skill_git', 'related_to'),
('cw_rel_ee_sql', 'cw_major_ee', 'cw_skill_sql', 'related_to'),
-- Math major → skills
('cw_rel_math_python', 'cw_major_math', 'cw_skill_python', 'required_by'),
('cw_rel_math_sql', 'cw_major_math', 'cw_skill_sql', 'required_by'),
('cw_rel_math_ml', 'cw_major_math', 'cw_skill_machine_learning', 'related_to'),
('cw_rel_math_da', 'cw_major_math', 'cw_skill_data_analysis', 'related_to'),
('cw_rel_math_excel', 'cw_major_math', 'cw_skill_excel', 'required_by'),
-- Stat major → skills
('cw_rel_stat_python', 'cw_major_stat', 'cw_skill_python', 'required_by'),
('cw_rel_stat_sql', 'cw_major_stat', 'cw_skill_sql', 'required_by'),
('cw_rel_stat_da', 'cw_major_stat', 'cw_skill_data_analysis', 'required_by'),
('cw_rel_stat_ml', 'cw_major_stat', 'cw_skill_machine_learning', 'required_by'),
('cw_rel_stat_excel', 'cw_major_stat', 'cw_skill_excel', 'required_by'),
-- IS major → skills
('cw_rel_is_sql', 'cw_major_is', 'cw_skill_sql', 'required_by'),
('cw_rel_is_python', 'cw_major_is', 'cw_skill_python', 'required_by'),
('cw_rel_is_da', 'cw_major_is', 'cw_skill_data_analysis', 'required_by'),
('cw_rel_is_excel', 'cw_major_is', 'cw_skill_excel', 'required_by'),
('cw_rel_is_js', 'cw_major_is', 'cw_skill_javascript', 'related_to'),
-- Auto major → skills
('cw_rel_auto_cpp', 'cw_major_auto', 'cw_skill_cpp', 'required_by'),
('cw_rel_auto_python', 'cw_major_auto', 'cw_skill_python', 'required_by'),
('cw_rel_auto_linux', 'cw_major_auto', 'cw_skill_linux', 'required_by'),
('cw_rel_auto_git', 'cw_major_auto', 'cw_skill_git', 'related_to'),
-- Comm major → skills
('cw_rel_comm_cpp', 'cw_major_comm', 'cw_skill_cpp', 'required_by'),
('cw_rel_comm_python', 'cw_major_comm', 'cw_skill_python', 'required_by'),
('cw_rel_comm_linux', 'cw_major_comm', 'cw_skill_linux', 'required_by'),
-- Finance major → skills
('cw_rel_fin_excel', 'cw_major_finance', 'cw_skill_excel', 'required_by'),
('cw_rel_fin_sql', 'cw_major_finance', 'cw_skill_sql', 'required_by'),
('cw_rel_fin_python', 'cw_major_finance', 'cw_skill_python', 'related_to'),
('cw_rel_fin_da', 'cw_major_finance', 'cw_skill_data_analysis', 'related_to'),
-- EC major → skills
('cw_rel_ecom_js', 'cw_major_ecom', 'cw_skill_javascript', 'required_by'),
('cw_rel_ecom_sql', 'cw_major_ecom', 'cw_skill_sql', 'required_by'),
('cw_rel_ecom_python', 'cw_major_ecom', 'cw_skill_python', 'related_to'),
-- Design major → skills
('cw_rel_design_js', 'cw_major_design', 'cw_skill_javascript', 'required_by'),
('cw_rel_design_react', 'cw_major_design', 'cw_skill_react', 'required_by'),
('cw_rel_design_vue', 'cw_major_design', 'cw_skill_vue', 'related_to'),
-- Physics major → skills
('cw_rel_phys_python', 'cw_major_physics', 'cw_skill_python', 'required_by'),
('cw_rel_phys_ml', 'cw_major_physics', 'cw_skill_machine_learning', 'related_to'),

-- Role → skill mappings
('cw_rel_role_backend_java', 'cw_role_backend_engineer', 'cw_skill_java', 'required_by'),
('cw_rel_role_backend_python', 'cw_role_backend_engineer', 'cw_skill_python', 'required_by'),
('cw_rel_role_backend_sql', 'cw_role_backend_engineer', 'cw_skill_sql', 'required_by'),
('cw_rel_role_backend_git', 'cw_role_backend_engineer', 'cw_skill_git', 'required_by'),
('cw_rel_role_backend_linux', 'cw_role_backend_engineer', 'cw_skill_linux', 'required_by'),
('cw_rel_role_backend_docker', 'cw_role_backend_engineer', 'cw_skill_docker', 'required_by'),
('cw_rel_role_backend_spring', 'cw_role_backend_engineer', 'cw_skill_spring', 'related_to'),
('cw_rel_role_backend_go', 'cw_role_backend_engineer', 'cw_skill_go', 'related_to'),
('cw_rel_role_frontend_js', 'cw_role_frontend_engineer', 'cw_skill_javascript', 'required_by'),
('cw_rel_role_frontend_react', 'cw_role_frontend_engineer', 'cw_skill_react', 'required_by'),
('cw_rel_role_frontend_vue', 'cw_role_frontend_engineer', 'cw_skill_vue', 'required_by'),
('cw_rel_role_frontend_git', 'cw_role_frontend_engineer', 'cw_skill_git', 'required_by'),
('cw_rel_role_frontend_python', 'cw_role_frontend_engineer', 'cw_skill_python', 'related_to'),
('cw_rel_role_da_sql', 'cw_role_data_analyst', 'cw_skill_sql', 'required_by'),
('cw_rel_role_da_python', 'cw_role_data_analyst', 'cw_skill_python', 'required_by'),
('cw_rel_role_da_excel', 'cw_role_data_analyst', 'cw_skill_excel', 'required_by'),
('cw_rel_role_da_da', 'cw_role_data_analyst', 'cw_skill_data_analysis', 'required_by'),
('cw_rel_role_da_ml', 'cw_role_data_analyst', 'cw_skill_machine_learning', 'related_to'),
('cw_rel_role_alg_python', 'cw_role_algorithm_engineer', 'cw_skill_python', 'required_by'),
('cw_rel_role_alg_ml', 'cw_role_algorithm_engineer', 'cw_skill_machine_learning', 'required_by'),
('cw_rel_role_alg_dl', 'cw_role_algorithm_engineer', 'cw_skill_deep_learning', 'required_by'),
('cw_rel_role_alg_cpp', 'cw_role_algorithm_engineer', 'cw_skill_cpp', 'related_to'),
('cw_rel_role_pm_comm', 'cw_role_product_manager', 'cw_skill_communication', 'required_by'),
('cw_rel_role_pm_team', 'cw_role_product_manager', 'cw_skill_teamwork', 'required_by'),
('cw_rel_role_pm_pm', 'cw_role_product_manager', 'cw_skill_project_management', 'required_by'),
('cw_rel_role_pm_da', 'cw_role_product_manager', 'cw_skill_data_analysis', 'required_by'),
('cw_rel_role_pm_sql', 'cw_role_product_manager', 'cw_skill_sql', 'related_to'),
('cw_rel_role_test_python', 'cw_role_test_engineer', 'cw_skill_python', 'required_by'),
('cw_rel_role_test_sql', 'cw_role_test_engineer', 'cw_skill_sql', 'required_by'),
('cw_rel_role_test_linux', 'cw_role_test_engineer', 'cw_skill_linux', 'required_by'),
('cw_rel_role_test_docker', 'cw_role_test_engineer', 'cw_skill_docker', 'related_to'),
('cw_rel_role_devops_linux', 'cw_role_devops_engineer', 'cw_skill_linux', 'required_by'),
('cw_rel_role_devops_docker', 'cw_role_devops_engineer', 'cw_skill_docker', 'required_by'),
('cw_rel_role_devops_python', 'cw_role_devops_engineer', 'cw_skill_python', 'required_by'),
('cw_rel_role_devops_go', 'cw_role_devops_engineer', 'cw_skill_go', 'related_to'),
('cw_rel_role_ds_python', 'cw_role_data_scientist', 'cw_skill_python', 'required_by'),
('cw_rel_role_ds_sql', 'cw_role_data_scientist', 'cw_skill_sql', 'required_by'),
('cw_rel_role_ds_ml', 'cw_role_data_scientist', 'cw_skill_machine_learning', 'required_by'),
('cw_rel_role_ds_dl', 'cw_role_data_scientist', 'cw_skill_deep_learning', 'required_by'),
('cw_rel_role_fullstack_js', 'cw_role_fullstack_engineer', 'cw_skill_javascript', 'required_by'),
('cw_rel_role_fullstack_python', 'cw_role_fullstack_engineer', 'cw_skill_python', 'required_by'),
('cw_rel_role_fullstack_sql', 'cw_role_fullstack_engineer', 'cw_skill_sql', 'required_by'),
('cw_rel_role_fullstack_docker', 'cw_role_fullstack_engineer', 'cw_skill_docker', 'related_to'),
('cw_rel_role_ux_js', 'cw_role_ux_designer', 'cw_skill_javascript', 'related_to'),
('cw_rel_role_ux_react', 'cw_role_ux_designer', 'cw_skill_react', 'related_to'),

-- Major → role mappings
('cw_rel_major_cs_role_backend', 'cw_major_cs', 'cw_role_backend_engineer', 'maps_to'),
('cw_rel_major_cs_role_frontend', 'cw_major_cs', 'cw_role_frontend_engineer', 'maps_to'),
('cw_rel_major_cs_role_fullstack', 'cw_major_cs', 'cw_role_fullstack_engineer', 'maps_to'),
('cw_rel_major_cs_role_alg', 'cw_major_cs', 'cw_role_algorithm_engineer', 'maps_to'),
('cw_rel_major_se_role_backend', 'cw_major_se', 'cw_role_backend_engineer', 'maps_to'),
('cw_rel_major_se_role_fullstack', 'cw_major_se', 'cw_role_fullstack_engineer', 'maps_to'),
('cw_rel_major_se_role_test', 'cw_major_se', 'cw_role_test_engineer', 'maps_to'),
('cw_rel_major_ds_role_da', 'cw_major_ds', 'cw_role_data_analyst', 'maps_to'),
('cw_rel_major_ds_role_ds', 'cw_major_ds', 'cw_role_data_scientist', 'maps_to'),
('cw_rel_major_ai_role_alg', 'cw_major_ai', 'cw_role_algorithm_engineer', 'maps_to'),
('cw_rel_major_ai_role_ds', 'cw_major_ai', 'cw_role_data_scientist', 'maps_to'),
('cw_rel_major_ee_role_backend', 'cw_major_ee', 'cw_role_backend_engineer', 'maps_to'),
('cw_rel_major_stat_role_da', 'cw_major_stat', 'cw_role_data_analyst', 'maps_to'),
('cw_rel_major_stat_role_ds', 'cw_major_stat', 'cw_role_data_scientist', 'maps_to');

-- ── Observations (~150) ──────────────────────────────────────────

INSERT OR IGNORE INTO cw_observations (id, entity_id, observation_type, support_count, sample_size, source) VALUES
-- Skill demand observations (how often skills appear in job postings / student profiles)
('cw_obs_python_demand', 'cw_skill_python', 'demand_frequency', 85, 100, 'seed'),
('cw_obs_sql_demand', 'cw_skill_sql', 'demand_frequency', 90, 100, 'seed'),
('cw_obs_java_demand', 'cw_skill_java', 'demand_frequency', 75, 100, 'seed'),
('cw_obs_js_demand', 'cw_skill_javascript', 'demand_frequency', 70, 100, 'seed'),
('cw_obs_ml_demand', 'cw_skill_machine_learning', 'demand_frequency', 45, 100, 'seed'),
('cw_obs_dl_demand', 'cw_skill_deep_learning', 'demand_frequency', 25, 100, 'seed'),
('cw_obs_da_demand', 'cw_skill_data_analysis', 'demand_frequency', 60, 100, 'seed'),
('cw_obs_excel_demand', 'cw_skill_excel', 'demand_frequency', 55, 100, 'seed'),
('cw_obs_linux_demand', 'cw_skill_linux', 'demand_frequency', 55, 100, 'seed'),
('cw_obs_git_demand', 'cw_skill_git', 'demand_frequency', 80, 100, 'seed'),
('cw_obs_docker_demand', 'cw_skill_docker', 'demand_frequency', 50, 100, 'seed'),
('cw_obs_go_demand', 'cw_skill_go', 'demand_frequency', 20, 100, 'seed'),
('cw_obs_cpp_demand', 'cw_skill_cpp', 'demand_frequency', 35, 100, 'seed'),
('cw_obs_react_demand', 'cw_skill_react', 'demand_frequency', 50, 100, 'seed'),
('cw_obs_vue_demand', 'cw_skill_vue', 'demand_frequency', 40, 100, 'seed'),
('cw_obs_spring_demand', 'cw_skill_spring', 'demand_frequency', 30, 100, 'seed'),
('cw_obs_django_demand', 'cw_skill_django', 'demand_frequency', 15, 100, 'seed'),
('cw_obs_comm_demand', 'cw_skill_communication', 'demand_frequency', 65, 100, 'seed'),
('cw_obs_team_demand', 'cw_skill_teamwork', 'demand_frequency', 70, 100, 'seed'),
('cw_obs_pm_demand', 'cw_skill_project_management', 'demand_frequency', 40, 100, 'seed'),

-- Role demand observations
('cw_obs_role_backend_demand', 'cw_role_backend_engineer', 'demand_frequency', 80, 100, 'seed'),
('cw_obs_role_frontend_demand', 'cw_role_frontend_engineer', 'demand_frequency', 65, 100, 'seed'),
('cw_obs_role_da_demand', 'cw_role_data_analyst', 'demand_frequency', 75, 100, 'seed'),
('cw_obs_role_alg_demand', 'cw_role_algorithm_engineer', 'demand_frequency', 40, 100, 'seed'),
('cw_obs_role_pm_demand', 'cw_role_product_manager', 'demand_frequency', 55, 100, 'seed'),
('cw_obs_role_test_demand', 'cw_role_test_engineer', 'demand_frequency', 50, 100, 'seed'),
('cw_obs_role_devops_demand', 'cw_role_devops_engineer', 'demand_frequency', 30, 100, 'seed'),
('cw_obs_role_ds_demand', 'cw_role_data_scientist', 'demand_frequency', 35, 100, 'seed'),
('cw_obs_role_fullstack_demand', 'cw_role_fullstack_engineer', 'demand_frequency', 45, 100, 'seed'),
('cw_obs_role_ux_demand', 'cw_role_ux_designer', 'demand_frequency', 30, 100, 'seed'),

-- Skill mastery rates for specific roles (by role)
('cw_obs_backend_java_mastery', 'cw_skill_java', 'mastery_rate:backend_engineer', 40, 80, 'seed'),
('cw_obs_backend_python_mastery', 'cw_skill_python', 'mastery_rate:backend_engineer', 60, 80, 'seed'),
('cw_obs_backend_sql_mastery', 'cw_skill_sql', 'mastery_rate:backend_engineer', 55, 80, 'seed'),
('cw_obs_backend_linux_mastery', 'cw_skill_linux', 'mastery_rate:backend_engineer', 45, 80, 'seed'),
('cw_obs_backend_docker_mastery', 'cw_skill_docker', 'mastery_rate:backend_engineer', 30, 80, 'seed'),
('cw_obs_backend_git_mastery', 'cw_skill_git', 'mastery_rate:backend_engineer', 65, 80, 'seed'),

('cw_obs_frontend_js_mastery', 'cw_skill_javascript', 'mastery_rate:frontend_engineer', 55, 65, 'seed'),
('cw_obs_frontend_react_mastery', 'cw_skill_react', 'mastery_rate:frontend_engineer', 40, 65, 'seed'),
('cw_obs_frontend_vue_mastery', 'cw_skill_vue', 'mastery_rate:frontend_engineer', 35, 65, 'seed'),
('cw_obs_frontend_git_mastery', 'cw_skill_git', 'mastery_rate:frontend_engineer', 50, 65, 'seed'),

('cw_obs_da_sql_mastery', 'cw_skill_sql', 'mastery_rate:data_analyst', 55, 75, 'seed'),
('cw_obs_da_python_mastery', 'cw_skill_python', 'mastery_rate:data_analyst', 45, 75, 'seed'),
('cw_obs_da_excel_mastery', 'cw_skill_excel', 'mastery_rate:data_analyst', 60, 75, 'seed'),
('cw_obs_da_da_mastery', 'cw_skill_data_analysis', 'mastery_rate:data_analyst', 40, 75, 'seed'),
('cw_obs_da_ml_mastery', 'cw_skill_machine_learning', 'mastery_rate:data_analyst', 20, 75, 'seed'),

('cw_obs_alg_python_mastery', 'cw_skill_python', 'mastery_rate:algorithm_engineer', 65, 40, 'seed'),
('cw_obs_alg_ml_mastery', 'cw_skill_machine_learning', 'mastery_rate:algorithm_engineer', 30, 40, 'seed'),
('cw_obs_alg_dl_mastery', 'cw_skill_deep_learning', 'mastery_rate:algorithm_engineer', 25, 40, 'seed'),

('cw_obs_pm_comm_mastery', 'cw_skill_communication', 'mastery_rate:product_manager', 50, 55, 'seed'),
('cw_obs_pm_team_mastery', 'cw_skill_teamwork', 'mastery_rate:product_manager', 55, 55, 'seed'),
('cw_obs_pm_da_mastery', 'cw_skill_data_analysis', 'mastery_rate:product_manager', 30, 55, 'seed'),

-- Skill in_progress rates for roles
('cw_obs_backend_java_ip', 'cw_skill_java', 'in_progress_rate:backend_engineer', 35, 80, 'seed'),
('cw_obs_backend_docker_ip', 'cw_skill_docker', 'in_progress_rate:backend_engineer', 40, 80, 'seed'),
('cw_obs_frontend_react_ip', 'cw_skill_react', 'in_progress_rate:frontend_engineer', 30, 65, 'seed'),
('cw_obs_da_ml_ip', 'cw_skill_machine_learning', 'in_progress_rate:data_analyst', 35, 75, 'seed'),
('cw_obs_alg_dl_ip', 'cw_skill_deep_learning', 'in_progress_rate:algorithm_engineer', 45, 40, 'seed'),

-- Industry growth observations
('cw_obs_internet_growth', 'cw_industry_internet', 'hiring_growth_rate', 15, 100, 'seed'),
('cw_obs_finance_growth', 'cw_industry_finance', 'hiring_growth_rate', 5, 100, 'seed'),
('cw_obs_edu_growth', 'cw_industry_education', 'hiring_growth_rate', 8, 100, 'seed'),
('cw_obs_health_growth', 'cw_industry_healthcare', 'hiring_growth_rate', 12, 100, 'seed'),
('cw_obs_ecom_growth', 'cw_industry_ecommerce', 'hiring_growth_rate', 18, 100, 'seed'),

-- Major → skill mention observations (by students)
('cw_obs_cs_python_mention', 'cw_skill_python', 'student_mention:cs', 90, 100, 'seed'),
('cw_obs_cs_java_mention', 'cw_skill_java', 'student_mention:cs', 75, 100, 'seed'),
('cw_obs_cs_sql_mention', 'cw_skill_sql', 'student_mention:cs', 70, 100, 'seed'),
('cw_obs_cs_linux_mention', 'cw_skill_linux', 'student_mention:cs', 50, 100, 'seed'),
('cw_obs_cs_js_mention', 'cw_skill_javascript', 'student_mention:cs', 55, 100, 'seed'),
('cw_obs_cs_git_mention', 'cw_skill_git', 'student_mention:cs', 60, 100, 'seed'),
('cw_obs_cs_ml_mention', 'cw_skill_machine_learning', 'student_mention:cs', 30, 100, 'seed'),

('cw_obs_se_java_mention', 'cw_skill_java', 'student_mention:se', 80, 100, 'seed'),
('cw_obs_se_python_mention', 'cw_skill_python', 'student_mention:se', 70, 100, 'seed'),
('cw_obs_se_sql_mention', 'cw_skill_sql', 'student_mention:se', 65, 100, 'seed'),
('cw_obs_se_js_mention', 'cw_skill_javascript', 'student_mention:se', 60, 100, 'seed'),
('cw_obs_se_git_mention', 'cw_skill_git', 'student_mention:se', 65, 100, 'seed'),
('cw_obs_se_spring_mention', 'cw_skill_spring', 'student_mention:se', 40, 100, 'seed'),

('cw_obs_ds_python_mention', 'cw_skill_python', 'student_mention:ds', 85, 100, 'seed'),
('cw_obs_ds_sql_mention', 'cw_skill_sql', 'student_mention:ds', 80, 100, 'seed'),
('cw_obs_ds_ml_mention', 'cw_skill_machine_learning', 'student_mention:ds', 55, 100, 'seed'),
('cw_obs_ds_da_mention', 'cw_skill_data_analysis', 'student_mention:ds', 65, 100, 'seed'),
('cw_obs_ds_excel_mention', 'cw_skill_excel', 'student_mention:ds', 50, 100, 'seed'),

('cw_obs_ai_python_mention', 'cw_skill_python', 'student_mention:ai', 90, 100, 'seed'),
('cw_obs_ai_ml_mention', 'cw_skill_machine_learning', 'student_mention:ai', 75, 100, 'seed'),
('cw_obs_ai_dl_mention', 'cw_skill_deep_learning', 'student_mention:ai', 60, 100, 'seed'),
('cw_obs_ai_sql_mention', 'cw_skill_sql', 'student_mention:ai', 50, 100, 'seed'),

('cw_obs_ee_cpp_mention', 'cw_skill_cpp', 'student_mention:ee', 70, 100, 'seed'),
('cw_obs_ee_python_mention', 'cw_skill_python', 'student_mention:ee', 55, 100, 'seed'),
('cw_obs_ee_linux_mention', 'cw_skill_linux', 'student_mention:ee', 45, 100, 'seed'),

('cw_obs_math_python_mention', 'cw_skill_python', 'student_mention:math', 60, 100, 'seed'),
('cw_obs_math_sql_mention', 'cw_skill_sql', 'student_mention:math', 50, 100, 'seed'),
('cw_obs_math_ml_mention', 'cw_skill_machine_learning', 'student_mention:math', 35, 100, 'seed'),

('cw_obs_stat_python_mention', 'cw_skill_python', 'student_mention:stat', 70, 100, 'seed'),
('cw_obs_stat_sql_mention', 'cw_skill_sql', 'student_mention:stat', 65, 100, 'seed'),
('cw_obs_stat_da_mention', 'cw_skill_data_analysis', 'student_mention:stat', 55, 100, 'seed'),
('cw_obs_stat_ml_mention', 'cw_skill_machine_learning', 'student_mention:stat', 40, 100, 'seed'),

('cw_obs_is_sql_mention', 'cw_skill_sql', 'student_mention:is', 65, 100, 'seed'),
('cw_obs_is_python_mention', 'cw_skill_python', 'student_mention:is', 55, 100, 'seed'),
('cw_obs_is_excel_mention', 'cw_skill_excel', 'student_mention:is', 60, 100, 'seed'),

-- Additional demand frequency observations
('cw_obs_role_backend_salary', 'cw_role_backend_engineer', 'avg_salary_k', 25, 100, 'seed'),
('cw_obs_role_frontend_salary', 'cw_role_frontend_engineer', 'avg_salary_k', 22, 100, 'seed'),
('cw_obs_role_da_salary', 'cw_role_data_analyst', 'avg_salary_k', 20, 100, 'seed'),
('cw_obs_role_alg_salary', 'cw_role_algorithm_engineer', 'avg_salary_k', 35, 100, 'seed'),
('cw_obs_role_pm_salary', 'cw_role_product_manager', 'avg_salary_k', 25, 100, 'seed'),
('cw_obs_role_test_salary', 'cw_role_test_engineer', 'avg_salary_k', 18, 100, 'seed'),
('cw_obs_role_devops_salary', 'cw_role_devops_engineer', 'avg_salary_k', 25, 100, 'seed'),
('cw_obs_role_ds_salary', 'cw_role_data_scientist', 'avg_salary_k', 32, 100, 'seed'),
('cw_obs_role_fullstack_salary', 'cw_role_fullstack_engineer', 'avg_salary_k', 28, 100, 'seed'),
('cw_obs_role_ux_salary', 'cw_role_ux_designer', 'avg_salary_k', 20, 100, 'seed'),

-- Role median experience requirement
('cw_obs_backend_exp', 'cw_role_backend_engineer', 'median_exp_years', 3, 100, 'seed'),
('cw_obs_frontend_exp', 'cw_role_frontend_engineer', 'median_exp_years', 3, 100, 'seed'),
('cw_obs_da_exp', 'cw_role_data_analyst', 'median_exp_years', 2, 100, 'seed'),
('cw_obs_alg_exp', 'cw_role_algorithm_engineer', 'median_exp_years', 5, 100, 'seed'),
('cw_obs_pm_exp', 'cw_role_product_manager', 'median_exp_years', 3, 100, 'seed'),
('cw_obs_test_exp', 'cw_role_test_engineer', 'median_exp_years', 2, 100, 'seed'),
('cw_obs_devops_exp', 'cw_role_devops_engineer', 'median_exp_years', 3, 100, 'seed'),
('cw_obs_ds_exp', 'cw_role_data_scientist', 'median_exp_years', 4, 100, 'seed'),
('cw_obs_fullstack_exp', 'cw_role_fullstack_engineer', 'median_exp_years', 3, 100, 'seed'),
('cw_obs_ux_exp', 'cw_role_ux_designer', 'median_exp_years', 3, 100, 'seed'),

-- Graduate hiring ratios
('cw_obs_backend_grad', 'cw_role_backend_engineer', 'grad_hiring_ratio', 60, 100, 'seed'),
('cw_obs_frontend_grad', 'cw_role_frontend_engineer', 'grad_hiring_ratio', 65, 100, 'seed'),
('cw_obs_da_grad', 'cw_role_data_analyst', 'grad_hiring_ratio', 70, 100, 'seed'),
('cw_obs_alg_grad', 'cw_role_algorithm_engineer', 'grad_hiring_ratio', 35, 100, 'seed'),
('cw_obs_pm_grad', 'cw_role_product_manager', 'grad_hiring_ratio', 45, 100, 'seed'),
('cw_obs_test_grad', 'cw_role_test_engineer', 'grad_hiring_ratio', 75, 100, 'seed'),
('cw_obs_devops_grad', 'cw_role_devops_engineer', 'grad_hiring_ratio', 40, 100, 'seed'),
('cw_obs_ds_grad', 'cw_role_data_scientist', 'grad_hiring_ratio', 30, 100, 'seed'),
('cw_obs_fullstack_grad', 'cw_role_fullstack_engineer', 'grad_hiring_ratio', 40, 100, 'seed'),
('cw_obs_ux_grad', 'cw_role_ux_designer', 'grad_hiring_ratio', 50, 100, 'seed'),

-- Skill difficulty-level observations
('cw_obs_python_beginner', 'cw_skill_python', 'beginner_friendly_ratio', 80, 100, 'seed'),
('cw_obs_sql_beginner', 'cw_skill_sql', 'beginner_friendly_ratio', 85, 100, 'seed'),
('cw_obs_java_beginner', 'cw_skill_java', 'beginner_friendly_ratio', 55, 100, 'seed'),
('cw_obs_js_beginner', 'cw_skill_javascript', 'beginner_friendly_ratio', 75, 100, 'seed'),
('cw_obs_ml_beginner', 'cw_skill_machine_learning', 'beginner_friendly_ratio', 20, 100, 'seed'),
('cw_obs_dl_beginner', 'cw_skill_deep_learning', 'beginner_friendly_ratio', 10, 100, 'seed'),
('cw_obs_react_beginner', 'cw_skill_react', 'beginner_friendly_ratio', 45, 100, 'seed'),
('cw_obs_docker_beginner', 'cw_skill_docker', 'beginner_friendly_ratio', 30, 100, 'seed'),
('cw_obs_git_beginner', 'cw_skill_git', 'beginner_friendly_ratio', 90, 100, 'seed'),
('cw_obs_excel_beginner', 'cw_skill_excel', 'beginner_friendly_ratio', 95, 100, 'seed');
